Ejercicio 1 Hacer una matriz 8x8 empezando en 1 llenado por filas

In [1]:
import numpy as np

matriz = [[(i*8+j+1)for j in range(8)]for i in range (8)]
m =np.array(matriz)
m


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

#Ejercicio 2 Hacer una matriz 8x8 empezando en 1 llenado por columnas

In [2]:


matriz2 = np.arange(1, 65).reshape((8, 8), order='F')
matriz2



array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

Ejercicio 2 reemplazar los elementos que tengan al menos un 3 por -99.

 



In [5]:


matriz2[matriz2 % 10 == 3] = -99

matriz2

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26,  34,  42,  50,  58],
       [-99,  11,  19,  27,  35, -99,  51,  59],
       [  4,  12,  20,  28,  36,  44,  52,  60],
       [  5, -99,  21,  29,  37,  45, -99,  61],
       [  6,  14,  22,  30,  38,  46,  54,  62],
       [  7,  15, -99,  31,  39,  47,  55, -99],
       [  8,  16,  24,  32,  40,  48,  56,  64]])

Ejercicio 3:

i. Reproducir la matriz B:

[[0.4 0.41 0.42 0.43 0.44]
[0.45 0.46 0.47 0.48 0.49]
[0.5 0.51 0.52 0.53 0.54]
[0.55 0.56 0.57 0.58 0.59]
[0.6 0.61 0.62 0.63 0.64]
[0.65 0.66 0.67 0.68 0.69]
[0.7 0.71 0.72 0.73 0.74]
[0.75 0.76 0.77 0.78 0.79]]

ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas.

iii. Agregar una linea al final con el promedio de cada columna

iv. Agregar una columna al final con el valor maximo de cada fila

v. Guardar en un archivo.

In [12]:
#Creamos una matriz B
B = np.arange(0.4,0.80,0.01).reshape(8,5)
#unimos
MatrizU = np.concatenate((matriz2,B), axis =1)

#realizamos una linea al final con el promedio de cada columna
prom_colu = np.mean(MatrizU,axis = 0 ) 

Matriz3 = np.append(MatrizU,prom_colu).reshape(9,13)
#realizar columna con valor maximo  y ponerla al final
max_fil = np.max(Matriz3, axis =1)
Matriz4 = np.insert(Matriz3,[13],max_fil.reshape(9,1), axis =1)
#Guardado en un archivo
f = open('Matriz_E3.txt','w')
f.write('----------------------------------------')
f.write('\n Matriz Ejercicio 3\n' )
f.write(str(Matriz4))
f.write('\n----------------------------------------')
f.close()
