Ejercicio 1 Hacer una matriz 8x8 empezando en 1 llenado por filas

In [7]:
import numpy as np

matriz = [[(i*8+j+1)for j in range(8)]for i in range (8)]
m =np.array(matriz)
m


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

#Ejercicio 2 Hacer una matriz 8x8 empezando en 1 llenado por columnas

In [8]:
import numpy as np

matriz2 = np.arange(1, 65).reshape((8, 8), order='F')
matriz2



array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

Ejercicio 2 reemplazar los elementos que tengan al menos un 3 por -99.

 



In [11]:


matriz2[matriz2 % 10 == 3] = -99

matriz

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26,  34,  42,  50,  58],
       [-99,  11,  19,  27,  35, -99,  51,  59],
       [  4,  12,  20,  28,  36,  44,  52,  60],
       [  5, -99,  21,  29,  37,  45, -99,  61],
       [  6,  14,  22,  30,  38,  46,  54,  62],
       [  7,  15, -99,  31,  39,  47,  55, -99],
       [  8,  16,  24,  32,  40,  48,  56,  64]])